services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: food-ordering
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: 0322!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: martin@martin.com
      PGADMIN_DEFAULT_PASSWORD: 0322!
    ports:
      - "5050:80"
    volumes:
      - ./volumes/postgres/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge